[package]
name = "moos-sys"
version = "0.2.0"
authors = ["Jason Klein <jason@jasonklein.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.0.48"
bindgen = "0.52.0"